### ISSUE TITLE
nvchad works only through sudo

### ISSUE THREAD

**Issue by Miradden** [nix-community/nix4nvchad#6] opened 2024-08-29 21:59 UTC
After following the installation instructions using flakes and home-manager, nvchad doesn't really work when running as my normal user. Some things work, like the file picker and the in-editor terminal, but most other things are buggy or don't work. For example, If I change the theme in nvchad, I get this error:
```
E5108: Error executing lua: vim/loader.lua:0: EACCES: permission denied: /home/mirad/.cache/nvim/luac/%home%mirad%.local%share%nvim%lazy%base46%lua%base46%term.luac                  
stack traceback:                                                                                                                                                                      
        [C]: in function 'assert'                                                                                                                                                     
        vim/loader.lua: in function 'write'                                                                                                                                           
        vim/loader.lua: in function 'loadfile'                                                                                                                                        
        vim/loader.lua: in function <vim/loader.lua:0>                                                                                                                                
        [C]: in function 'require'                                                                                                                                                    
        .../mirad/.local/share/nvim/lazy/base46/lua/base46/init.lua:150: in function 'compile'                                                                                        
        .../mirad/.local/share/nvim/lazy/base46/lua/base46/init.lua:155: in function 'load_all_highlights'                                                                            
        .../share/nvim/lazy/ui/lua/telescope/_extensions/themes.lua:12: in function 'reload_theme'                                                                                    
        .../share/nvim/lazy/ui/lua/telescope/_extensions/themes.lua:60: in function 'run_replace_or_original'                                                                         
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'                                                                                        
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:292>
```
However if I quit nvim and then launch it again, the theme is applied. Another example is if I try running `:MasonInstallAll` it doesn't work at all and I get this error:
```
Command 'MasonInstallAll' not found after loading 'mason.nvim'
```
any icons also do not show up.

The really odd thing is that if I run `sudo nvim`, **everything works to my knowledge**. 

I'm not sure if I'm missing anything in my nix files (I probably quadruple checked them, but it's still possible) or if I'm running into a bug. It's probably my fault and not a bug, but I figured i'd post anyway just in case. 

Here are the pertinent configs:

flake.nix:
```
{
  description = "Configuration flake";

  inputs = {
    # NixOS official package source, using the nixos-24.05 branch here
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";
    home-manager.url = "github:nix-community/home-manager/release-24.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    # auto ricing
    stylix.url = "github:danth/stylix";

    # NVChad
    nvchad4nix = {
      url = "github:NvChad/nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
 outputs = inputs@{ self, nixpkgs, home-manager, stylix, nixos-hardware, ... }: {
    nixosConfigurations = {
      pearlescent = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = {system = "x86_64-linux"; inherit inputs; };
        modules = [
          ./configuration.nix

          {  # <- # example to add the overlay to Nixpkgs:
            nixpkgs = {
              overlays = [
                (final: prev: {
                    nvchad = inputs.nvchad4nix.packages.x86_64-linux.nvchad;
                })
              ];
            };
          }
          
          # stylix theming
          stylix.nixosModules.stylix
          
          # hardware config for specifc device
          nixos-hardware.nixosModules.asus-zephyrus-ga402
 
          home-manager.nixosModules.home-manager
          {
            home-manager.backupFileExtension = "backup";
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.mirad = import ./home.nix;
            home-manager.extraSpecialArgs = {inherit inputs; system = "x86_64-linux";};

            # Optionally, use home-manager.extraSpecialArgs to pass
            # arguments to home.nix
          }
        ];
      };
    };
  };
}
```

home.nix:
```
{ config, inputs, pkgs, ... }:

{

  imports = [
    inputs.nvchad4nix.homeManagerModule
  ];

  programs = {
...
    nvchad = {
      enable = true;
      extraPackages = with pkgs; [
        nodePackages.bash-language-server
        docker-compose-language-service
        dockerfile-language-server-nodejs
        emmet-language-server
        nixd
        (python3.withPackages(ps: with ps; [
          python-lsp-server
          flake8
        ]))
      ];
      hm-activation = true;
      backup = true;
    }; # end nvchad
    
    home-manager = { # let home-maanger install and manage itself
      enable = true;
    };
  }; # end programs

```

I don't have anything related to nvchad in my configuration.nix so I'm not including it.

**Comment by MOIS3Y** [comment] 2024-08-31 04:25
@Miradden with `sudo` works because on startup it will copy to `/root/.config` `/root/.local`
The cache will also be in `/root/.cache`, it looks like Bot-wxt1221 is right about the problem.

Mason won't work in nix because nix puts everything in `/nix/store` and mason in `/usr/local/`

**Comment by Miradden** [comment] 2024-09-04 20:17
Okay so permissions were definitely part of the problem, there were 167 files owned by root. I changed that so that the permissions matched what they were supposed to be. However, the UI still wasn't loading, so i thought that removing the files from cache, config, and local would help because it would have to regenerate everything. Upon doing that and running nvim, it started downloading plugins on startup and eventually I got this error: 
```
Please update neovim version to v0.10 at least! NvChad only supports v0.10+                                                                                                           
Error detected while processing /home/mirad/.config/nvim/init.lua:                                                                                                                    
E5113: Error while calling lua chunk: cannot open /home/mirad/.local/share/nvim/nvchad/base46/defaults: No such file or directory                                                     
stack traceback:                                                                                                                                                                      
        [C]: in function 'dofile'                                                                                                                                                     
        /home/mirad/.config/nvim/init.lua:32: in main chunk 
```
Some UI elements are loading now, like the status bar at the bottom with some icons, but everything is black and white and the icons are rendering incorrectly. I tried setting nvchad.enable = false, running `nixos-rebuild switch`, and then setting nvchad.enable = true to reinstall nvchad, trying to get it to regenerate everything and I still get the same error. As usual, running with sudo still works. It seems like some folders in /home/mirad/.local/share/nvim are not being regenerated.

**Comment by MOIS3Y** [comment] 2024-09-08 07:18
@Miradden is your full NixOS configuration publicly available?
Try testing this [repository](https://github.com/MOIS3Y/nvchad4nix) all it does is simply copy the starter configuration from `/nix/store` to `~/.config/nvim`

Beforehand, it would be a good idea to clear everything from the old `nvim` configuration
 ```console
 sudo rm -r ~/.config/nvim* ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim/
 ```

**Comment by Miradden** [comment] 2024-09-10 22:14
[Here](https://github.com/Miradden/Nix) is the link to my entire /etc/nixos folder, all nixos configuration I have is there. I cleared everything out using the command you posted and tested the repo using `nix run github:MOIS3Y/nvchad4nix/v2.5#nvchad`, now nvim and nvchad work as expected. Is there something that I did wrong that prevented it from doing that automatically via my config?

**Comment by MOIS3Y** [comment] 2024-09-11 05:56
@Miradden you have a very clean and simple configuration, I just reproduced by copying the parts from your flake.nix and home.nix that belong to NvChad and everything works fine

flake.nix
```nix
    # NVChad snip
    nvchad4nix = {
      url = "github:NvChad/nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

home.nix
```nix
  programs = {
    nvchad = {
      enable = true;
      extraPackages = with pkgs; [
        nodePackages.bash-language-server
        emmet-language-server
        nixd
        (python3.withPackages(ps: with ps; [
          python-lsp-server
          flake8
        ]))
      ];
      hm-activation = true;
      backup = true;
    }; # end nvchad
  }; # end programs
```

I'm almost sure that the problem is either due to the fact that you did not completely remove artifacts from previous `neovim` configurations

```console
rm -rf ~/.config/nvim* ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim/
```

Try now to rebuild NixOS `nixos-rebuild switch`
If everything works, we'll close the issue.

**Closed** 2024-09-11 19:36 UTC
